services:
  graphics:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: graphics-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      # host.docker.internal — доступ к хостовому PostgreSQL из контейнера
      - DATABASE_DSN=postgresql+asyncpg://nylinary:null@host.docker.internal:5432/nexora
      - REDIS_HOST=redis
      - NATS_HOSTS=nats://nats:4222
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_started
      nats:
        condition: service_started
    networks:
      - graphics_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: graphics-redis
    networks:
      - graphics_network
    restart: unless-stopped

  nats:
    image: nats:2-alpine
    container_name: graphics-nats
    command: ["-js", "-m", "8222"]
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      - graphics_network
    restart: unless-stopped

networks:
  graphics_network:
    name: graphics_network
